[[constraint]]
  revision = "f58b3a1827c1f4359397485d781c16f102e4b430"
  name = "github.com/cloudfoundry/bosh-cli"

[[constraint]]
  branch = "cli-patches"
  name = "github.com/jessevdk/go-flags"
  source = "github.com/cppforlife/go-flags"

[[constraint]]
  branch = "drop-stdout-logging"
  name = "github.com/cloudfoundry/socks5-proxy"
  source = "github.com/drich10/socks5-proxy"

[[override]]
  revision = "c1f48d5ce4f292dfb775ef52aaedd15be323510d"
  name = "github.com/cheggaaa/pb"

[[override]]
  revision = "90561c003f2f73d7cc61a013e5d84e08a75bc5b0"
  name = "github.com/pivotal-golang/s3cli"
  source = "github.com/cloudfoundry/bosh-s3cli"

[[override]]
  revision = "a960ab178e64b43d19051be6fd2891ff695bb206"
  name = "github.com/cloudfoundry/bosh-utils"
