---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: bosh-deployment-resource-ci
- name: bosh-deployment-resource
  path: gopath/src/github.com/cloudfoundry/bosh-deployment-resource

outputs:
- name: built-binaries

run:
  path: bosh-deployment-resource-ci/tasks/build.sh
