---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: bosh-deployment-resource-ci

outputs:
- name: tag-file

run:
  path: "/bin/sh"
  args:
  - -c
  - |
    set -e
    echo -n "$TAG" > tag-file/tag

params:
  TAG: ~